-- 07: 준비 서류 안내를 발급·준비 방법 중심으로 보완
-- 기존 JL_DOCUMENT_GUIDE의 언어별 안내문만 갱신합니다.
-- JL_DOCUMENT와 기존 테이블 구조는 변경하지 않습니다.

UPDATE JL_DOCUMENT_GUIDE SET description=N'本人確認と入国日を確認するための旅券です。', preparation_note=N'有効な旅券の原本を転入する方全員分用意します。旅券がない、または更新が必要な場合は、本国の旅券発給機関・大使館・領事館などの公式窓口で申請してください。' WHERE document_id=1 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'在留カードまたは特別永住者証明書など、在留資格を確認する証明書です。', preparation_note=N'在留カードは空港または出入国在留管理庁で交付されます。特別永住者証明書は住所地の市区町村窓口で確認してください。後日交付の場合は、転入届にパスポートを持参します。' WHERE document_id=2 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'パスポートで入国日を確認できない場合に補う資料です。', preparation_note=N'パスポートの入国日が確認できない場合は、搭乗券・航空会社の記録・荷物タグなど入国日を示す資料を用意し、受付可能な資料を港区に確認してください。' WHERE document_id=3 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'家族関係を確認する本国発行の原本と日本語訳です。', preparation_note=N'家族関係を示す原本は本国の公的機関または大使館・領事館などで取得し、日本語訳を添えてください。家族など2人以上で転入する場合に確認します。' WHERE document_id=4 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'マイナンバーを確認するためのカードです。', preparation_note=N'申請する場合は「個人番号カード交付申請書」を使います。郵送は申請書に必要事項と顔写真を用意して送付し、オンラインは申請書のQRコードから申請します。対応する証明写真機でもQRコードを使って申請できます。申請後は交付通知書を受け取り、指定された市区町村窓口でカードを受け取ります。' WHERE document_id=5 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'年金番号を確認する年金手帳または基礎年金番号通知書です。', preparation_note=N'2022年4月以降、初めて年金制度に加入する方には年金手帳ではなく基礎年金番号通知書が発行されます。手元にある年金手帳または通知書を持参し、紛失時は日本年金機構へ再交付を相談してください。' WHERE document_id=6 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'窓口で手続きをする方の本人確認に使う公的書類です。', preparation_note=N'パスポート・在留カードなど、港区が認める本人確認書類を用意します。代理人が届け出る場合は、委任状など追加書類が必要になることがあるため、事前に港区へ確認してください。' WHERE document_id=7 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'転入する外国人住民の在留資格を確認する証明書です。', preparation_note=N'転入する外国人住民全員分の在留カードまたは特別永住者証明書を持参します。カードが後日交付の場合はパスポートを持参するよう、港区の案内を確認してください。' WHERE document_id=8 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'前の市区町村から転出したことを示す証明書です。', preparation_note=N'前の市区町村の窓口または案内されたオンライン手続きで転出届を行い、交付された転出証明書を持参します。マイナンバーカードを使った転出では省略できる場合がありますが、カードの提示が必要です。' WHERE document_id=9 AND language_code='ja';
UPDATE JL_DOCUMENT_GUIDE SET description=N'マイナンバーを確認するためのカードです。', preparation_note=N'カードを持っている方全員分を持参します。マイナンバーカードを使って転出した場合は、転入届の受付でカードの提示が必要です。' WHERE document_id=10 AND language_code='ja';

UPDATE JL_DOCUMENT_GUIDE SET description=N'본인 확인과 입국일을 확인하는 여권입니다.', preparation_note=N'유효한 여권 원본을 전입하는 사람 전원분 준비합니다. 여권이 없거나 갱신이 필요하면 본국의 여권 발급기관·대사관·영사관 등 공식 창구에 신청해 주세요.' WHERE document_id=1 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'재류카드 또는 특별영주자증명서 등 재류자격을 확인하는 증명서입니다.', preparation_note=N'재류카드는 공항 또는 출입국재류관리청에서 교부됩니다. 특별영주자증명서는 주소지 시구정촌 창구에 확인해 주세요. 후일 교부 대상이면 전입신고 때 여권을 지참합니다.' WHERE document_id=2 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'여권으로 입국일을 확인할 수 없을 때 보완하는 자료입니다.', preparation_note=N'여권에서 입국일을 확인할 수 없으면 탑승권·항공사 기록·수하물 태그 등 입국일을 보여주는 자료를 준비하고, 접수 가능한 자료인지 미나토구에 확인해 주세요.' WHERE document_id=3 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'가족관계를 확인하기 위한 본국 발행 원본과 일본어 번역문입니다.', preparation_note=N'가족관계를 증명하는 원본은 본국의 공공기관 또는 대사관·영사관 등에서 발급받고 일본어 번역문을 첨부합니다. 가족 등 2명 이상이 전입할 때 확인합니다.' WHERE document_id=4 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'마이넘버를 확인하기 위한 카드입니다.', preparation_note=N'신청할 때는 「개인번호카드 교부신청서」를 사용합니다. 우편은 신청서에 필요한 사항과 얼굴 사진을 준비해 발송하고, 온라인은 신청서의 QR코드로 신청합니다. 신청 가능한 증명사진기에서도 QR코드로 신청할 수 있습니다. 신청 후 교부통지서를 받으면 지정된 지자체 창구에서 카드를 수령합니다.' WHERE document_id=5 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'연금번호를 확인하는 연금수첩 또는 기초연금번호 통지서입니다.', preparation_note=N'2022년 4월 이후 처음 연금제도에 가입하는 사람에게는 연금수첩 대신 기초연금번호 통지서가 발급됩니다. 가지고 있는 연금수첩 또는 통지서를 지참하고, 분실했다면 일본연금기구에 재발급을 문의해 주세요.' WHERE document_id=6 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'창구에서 절차를 진행하는 사람의 본인 확인에 사용하는 공적 서류입니다.', preparation_note=N'여권·재류카드 등 미나토구가 인정하는 본인확인서류를 준비합니다. 대리인이 신고하면 위임장 등 추가 서류가 필요할 수 있으므로 미리 미나토구에 확인해 주세요.' WHERE document_id=7 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'전입하는 외국인 주민의 재류자격을 확인하는 증명서입니다.', preparation_note=N'전입하는 외국인 주민 전원의 재류카드 또는 특별영주자증명서를 지참합니다. 카드가 후일 교부되는 경우에는 여권을 지참하라는 미나토구 안내를 확인해 주세요.' WHERE document_id=8 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'이전 시구정촌에서 전출했다는 것을 보여주는 증명서입니다.', preparation_note=N'이전 시구정촌 창구 또는 안내된 온라인 절차로 전출신고를 하고, 교부된 전출증명서를 지참합니다. 마이넘버카드를 이용한 전출은 생략할 수 있는 경우가 있지만 카드 제시가 필요합니다.' WHERE document_id=9 AND language_code='ko';
UPDATE JL_DOCUMENT_GUIDE SET description=N'마이넘버를 확인하기 위한 카드입니다.', preparation_note=N'카드를 가진 사람 전원의 카드를 지참합니다. 마이넘버카드를 이용해 전출했다면 전입신고 접수 때 카드 제시가 필요합니다.' WHERE document_id=10 AND language_code='ko';

UPDATE JL_DOCUMENT_GUIDE SET description=N'A passport used to confirm identity and the date of entry.', preparation_note=N'Prepare the original valid passport for everyone moving in. If a passport is missing or must be renewed, apply through an official passport office, embassy, or consulate in the issuing country.' WHERE document_id=1 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'A residence card or special permanent resident certificate used to confirm residence status.', preparation_note=N'Residence cards are issued at an airport or by the Immigration Services Agency. Check with the municipality about a special permanent resident certificate. If the card will be issued later, bring the passport for the moving-in notification.' WHERE document_id=2 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'Supporting material used when the entry date cannot be confirmed from the passport.', preparation_note=N'If the passport does not show the entry date, prepare a boarding pass, airline record, baggage tag, or similar evidence and confirm with Minato City that it can be accepted.' WHERE document_id=3 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'The original document issued in your home country and a Japanese translation used to confirm family relationships.', preparation_note=N'Obtain the original from an official authority, embassy, or consulate in your home country and attach a Japanese translation. This is checked when two or more family members move in.' WHERE document_id=4 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'A card used to confirm your My Number.', preparation_note=N'To apply, use the Individual Number Card application form. For mail, complete the form, prepare a face photo, and send it. For online applications, scan the QR code on the form. You can also apply at a participating photo booth using the QR code. After applying, receive the notification and collect the card at the designated municipal counter.' WHERE document_id=5 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'A pension book or Basic Pension Number Notice used to confirm your pension number.', preparation_note=N'Since April 2022, first-time pension participants receive a Basic Pension Number Notice instead of a pension book. Bring the document you have; if it is lost, ask the Japan Pension Service about reissue.' WHERE document_id=6 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'Official identification used to confirm the person visiting the service counter.', preparation_note=N'Prepare identification accepted by Minato City, such as a passport or residence card. If someone applies on your behalf, confirm in advance whether a power of attorney or other additional documents are required.' WHERE document_id=7 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'A certificate used to confirm the residence status of foreign residents moving in.', preparation_note=N'Bring a residence card or special permanent resident certificate for every foreign resident moving in. If the card will be issued later, check Minato City guidance about bringing the passport.' WHERE document_id=8 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'A certificate showing that you moved out of your previous municipality.', preparation_note=N'File the moving-out notification at the previous municipality or through its announced online process, then bring the issued moving-out certificate. It may be omitted when you used a My Number Card, but the card must be presented.' WHERE document_id=9 AND language_code='en';
UPDATE JL_DOCUMENT_GUIDE SET description=N'A card used to confirm your My Number.', preparation_note=N'Bring the card for everyone who has one. If you used a My Number Card to move out, it must be presented when the moving-in notification is accepted.' WHERE document_id=10 AND language_code='en';

UPDATE JL_DOCUMENT_I18N SET condition_text=N'마이넘버카드를 보유하고 있거나, 마이넘버카드를 이용해 전출신고를 한 경우에 해당합니다.' WHERE document_id=5 AND language_code='ko';
UPDATE JL_DOCUMENT_I18N SET condition_text=N'Applies when you have a My Number Card or used one for the moving-out notification.' WHERE document_id=5 AND language_code='en';
UPDATE JL_DOCUMENT SET condition_text=N'マイナンバーカードを持っている方、またはカードを使って転出届をした方が対象です。' WHERE id=5;

COMMIT;
