-- 08: 해외 전입 후 자주 필요한 생활행정 절차 추가
-- 02, 04, 07 실행 후 한 번만 실행하세요. 기존 ID 1~2, 문서 1~10과 중복되지 않는 ID를 사용합니다.

INSERT INTO JL_PROCEDURE (id,region_id,category_id,title,summary,eligibility,deadline_text,method_text,notice,situation,phase_code,published,revision) VALUES (3,2,1,N'国民健康保険の加入',N'会社の健康保険に入っていない人の医療保険手続き。',N'会社の健康保険やその扶養に入っていない住民。',N'港区に住み始めてから14日以内。',N'各総合支所の窓口サービス係または台場分室で届出。',N'勤務先の健康保険に加入する人は会社の手続きを確認してください。','ABROAD','AFTER_ARRIVAL','Y',1);
INSERT INTO JL_PROCEDURE (id,region_id,category_id,title,summary,eligibility,deadline_text,method_text,notice,situation,phase_code,published,revision) VALUES (4,2,1,N'国民年金の加入',N'会社の厚生年金に入らない人の公的年金手続き。',N'日本に住む20歳から59歳で、第2号・第3号被保険者でない人。',N'対象になった日から14日以内。',N'住所地の区役所または年金事務所で届出。',N'会社員は勤務先の厚生年金、扶養配偶者は第3号の条件を確認してください。','ABROAD','AFTER_ARRIVAL','Y',1);
INSERT INTO JL_PROCEDURE (id,region_id,category_id,title,summary,eligibility,deadline_text,method_text,notice,situation,phase_code,published,revision) VALUES (5,2,1,N'住民税の確認',N'前年所得と1月1日の住所を基準に税の扱いを確認。',N'前年に所得があり、課税基準日に日本国内の住所等がある人。',N'課税・申告時期は年度の案内を確認。',N'港区税務課または勤務先からの通知を確認。',N'入国初年度など前年所得がない場合は課税されるとは限りません。','ABROAD','DAILY_LIFE','Y',1);
INSERT INTO JL_PROCEDURE (id,region_id,category_id,title,summary,eligibility,deadline_text,method_text,notice,situation,phase_code,published,revision) VALUES (6,2,1,N'区立小中学校への入学',N'外国籍の子どもが港区立小中学校に通うための申請。',N'港区に住み、区立小中学校への入学を希望する外国籍の子ども。',N'入学時期により締切が異なるため早めに確認。',N'港区教育委員会学務課で申請。',N'日本語での手続きが難しい場合は通訳を用意してください。','ABROAD','WORK_OR_SCHOOL','Y',1);
INSERT INTO JL_PROCEDURE (id,region_id,category_id,title,summary,eligibility,deadline_text,method_text,notice,situation,phase_code,published,revision) VALUES (7,2,1,N'印鑑登録',N'契約等で印鑑証明書が必要な人の登録手続き。',N'港区に住民登録があり、15歳以上で意思能力がある人。',N'必要になった時に申請。',N'各総合支所区民課窓口サービス係で申請。',N'すべての人に必須ではありません。登録する印鑑の条件を確認してください。','ABROAD','DAILY_LIFE','Y',1);
INSERT INTO JL_PROCEDURE (id,region_id,category_id,title,summary,eligibility,deadline_text,method_text,notice,situation,phase_code,published,revision) VALUES (8,2,1,N'電気・ガス・水道の使用開始',N'入居した住宅でライフラインを使い始める手続き。',N'港区の住宅で電気・ガス・水道を使用する人。',N'入居日までに各事業者へ連絡。',N'契約する電力・ガス会社と東京都水道局へ申請。',N'賃貸契約書や管理会社の案内で契約先を確認してください。','ABROAD','DAILY_LIFE','Y',1);

INSERT INTO JL_PROCEDURE_I18N VALUES (3,'ko',N'국민건강보험 가입',N'회사 건강보험이 없는 사람의 의료보험 절차입니다.',N'회사 건강보험이나 그 피부양자가 아닌 주민입니다.',N'미나토구에 거주를 시작한 날부터 14일 이내입니다.',N'각 종합지소 창구서비스계 또는 다이바 분실에서 신고합니다.',N'회사 건강보험에 가입하는 사람은 회사 절차를 먼저 확인해 주세요.');
INSERT INTO JL_PROCEDURE_I18N VALUES (3,'en',N'Enroll in National Health Insurance',N'Health insurance procedures for people without employer health insurance.',N'Residents who are not covered by employee health insurance or its dependents.',N'Within 14 days after starting to live in Minato City.',N'File at a Regional City Office counter or the Daiba branch.',N'If you will join an employer plan, confirm your employer procedure.');
INSERT INTO JL_PROCEDURE_I18N VALUES (4,'ko',N'국민연금 가입',N'후생연금에 가입하지 않는 사람의 공적연금 절차입니다.',N'일본에 거주하는 20~59세 중 제2호·제3호 피보험자가 아닌 사람입니다.',N'대상이 된 날부터 14일 이내입니다.',N'주소지 구청 또는 연금사무소에서 신고합니다.',N'회사원은 후생연금, 피부양 배우자는 제3호 조건을 확인해 주세요.');
INSERT INTO JL_PROCEDURE_I18N VALUES (4,'en',N'Enroll in National Pension',N'Public pension procedures for people not covered by Employees’ Pension.',N'Residents aged 20 to 59 who are not Category II or III insured persons.',N'Within 14 days after becoming eligible.',N'File at the municipal office or a Japan Pension Service office.',N'Employees and dependent spouses should confirm their applicable category.');
INSERT INTO JL_PROCEDURE_I18N VALUES (5,'ko',N'주민세 확인',N'전년도 소득과 1월 1일 주소를 기준으로 세금 적용을 확인합니다.',N'전년도 소득이 있고 과세 기준일에 일본 주소 등이 있는 사람입니다.',N'과세·신고 시기는 해당 연도 안내를 확인합니다.',N'미나토구 세무과 또는 근무처의 통지를 확인합니다.',N'일본 입국 첫해 등 전년도 소득이 없으면 바로 과세된다고 단정할 수 없습니다.');
INSERT INTO JL_PROCEDURE_I18N VALUES (5,'en',N'Check Resident Tax',N'Check local tax treatment based on prior-year income and your address on January 1.',N'People with prior-year income and a qualifying address or property on the tax reference date.',N'Check the annual tax and filing schedule.',N'Check notices from Minato City Tax Division or your employer.',N'People arriving for the first time may not owe tax immediately if they had no prior-year income in Japan.');
INSERT INTO JL_PROCEDURE_I18N VALUES (6,'ko',N'구립 초·중학교 입학',N'외국 국적 자녀가 미나토구립 초·중학교에 다니기 위한 신청입니다.',N'미나토구에 거주하며 구립 초·중학교 입학을 희망하는 외국 국적 자녀입니다.',N'입학 시기에 따라 마감일이 다르므로 일찍 확인합니다.',N'미나토구 교육위원회 학무과에서 신청합니다.',N'일본어 절차가 어려우면 통역을 준비해 주세요.');
INSERT INTO JL_PROCEDURE_I18N VALUES (6,'en',N'Enroll in a Minato Municipal School',N'Application for foreign-national children who wish to attend a Minato municipal elementary or junior high school.',N'Foreign-national children residing in Minato City who wish to attend a municipal school.',N'Deadlines vary by enrollment period; confirm early.',N'Apply at the Minato City Board of Education School Affairs Section.',N'Arrange an interpreter if the procedure in Japanese is difficult.');
INSERT INTO JL_PROCEDURE_I18N VALUES (7,'ko',N'인감등록',N'계약 등으로 인감증명서가 필요한 사람의 등록 절차입니다.',N'미나토구 주민등록이 있고 만 15세 이상이며 의사능력이 있는 사람입니다.',N'필요할 때 신청합니다.',N'각 종합지소 구민과 창구서비스계에서 신청합니다.',N'모든 사람에게 필수는 아니며 등록할 인감의 조건을 확인해야 합니다.');
INSERT INTO JL_PROCEDURE_I18N VALUES (7,'en',N'Register a Personal Seal',N'Registration for people who need a seal certificate for contracts or other procedures.',N'Registered Minato residents aged 15 or older with decision-making capacity.',N'Apply when needed.',N'Apply at the Residents Support Section of a Regional City Office.',N'This is not mandatory for everyone; confirm the seal requirements.');
INSERT INTO JL_PROCEDURE_I18N VALUES (8,'ko',N'전기·가스·수도 사용 시작',N'입주한 주택에서 생활 인프라를 사용하기 위한 절차입니다.',N'미나토구 주택에서 전기·가스·수도를 사용할 사람입니다.',N'입주일까지 각 사업자에게 연락합니다.',N'계약할 전력·가스회사와 도쿄도 수도국에 신청합니다.',N'임대차계약서와 관리회사의 안내로 계약처를 확인해 주세요.');
INSERT INTO JL_PROCEDURE_I18N VALUES (8,'en',N'Start Electricity, Gas, and Water Service',N'Steps to start utilities at your new home in Minato City.',N'People who will use electricity, gas, and water at a Minato residence.',N'Contact each provider before the move-in date.',N'Apply to your electricity and gas providers and the Tokyo Metropolitan Waterworks Bureau.',N'Check your lease or property manager instructions for the correct providers.');

INSERT INTO JL_DOCUMENT VALUES (11,3,N'在留カード・パスポート','REQUIRED',N'外国人住民の本人確認に使用。',1);
INSERT INTO JL_DOCUMENT VALUES (12,4,N'基礎年金番号が分かる書類','CONDITIONAL',N'国民年金第1号の手続きに該当する場合。',1);
INSERT INTO JL_DOCUMENT VALUES (13,5,N'前年所得が分かる資料','CONDITIONAL',N'所得申告や課税確認が必要な場合。',1);
INSERT INTO JL_DOCUMENT VALUES (14,6,N'在留カード・パスポート','REQUIRED',N'子どもと保護者の住所等を確認する資料。',1);
INSERT INTO JL_DOCUMENT VALUES (15,7,N'登録する印鑑と在留カード','REQUIRED',N'本人申請で印鑑登録する場合。',1);
INSERT INTO JL_DOCUMENT VALUES (16,8,N'賃貸契約書・管理会社の案内','CONDITIONAL',N'各ライフラインの契約先を確認する場合。',1);

INSERT INTO JL_DOCUMENT_GUIDE VALUES (11,'ja',N'在留資格と本人を確認する書類です。',N'在留カードとパスポートを手元に用意します。');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (11,'ko',N'재류자격과 본인을 확인하는 서류입니다.',N'재류카드와 여권을 준비합니다.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (11,'en',N'Documents used to confirm identity and residence status.',N'Prepare your residence card and passport.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (12,'ja',N'基礎年金番号を確認する書類です。',N'年金手帳または基礎年金番号通知書を用意します。');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (12,'ko',N'기초연금번호를 확인하는 서류입니다.',N'연금수첩 또는 기초연금번호 통지서를 준비합니다.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (12,'en',N'Document used to confirm your Basic Pension Number.',N'Prepare your pension book or Basic Pension Number Notice.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (13,'ja',N'前年の所得を確認する資料です。',N'源泉徴収票など手元にある所得資料を用意します。');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (13,'ko',N'전년도 소득을 확인하는 자료입니다.',N'원천징수표 등 가지고 있는 소득 자료를 준비합니다.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (13,'en',N'Document used to confirm prior-year income.',N'Prepare available income records such as a withholding statement.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (14,'ja',N'子どもと保護者の住所等を確認する書類です。',N'子どもと保護者の在留カード・パスポートを用意します。');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (14,'ko',N'자녀와 보호자의 주소 등을 확인하는 서류입니다.',N'자녀와 보호자의 재류카드·여권을 준비합니다.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (14,'en',N'Documents confirming the child and guardian details.',N'Prepare the child and guardian residence cards and passports.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (15,'ja',N'印鑑登録に使う印鑑と本人確認書類です。',N'登録する印鑑と在留カードを用意します。');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (15,'ko',N'인감등록에 사용하는 인감과 본인확인서류입니다.',N'등록할 인감과 재류카드를 준비합니다.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (15,'en',N'The seal and identification used for seal registration.',N'Prepare the seal to register and your residence card.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (16,'ja',N'ライフラインの契約先を確認する資料です。',N'賃貸契約書や管理会社の案内を確認します。');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (16,'ko',N'생활 인프라 계약처를 확인하는 자료입니다.',N'임대차계약서와 관리회사의 안내를 확인합니다.');
INSERT INTO JL_DOCUMENT_GUIDE VALUES (16,'en',N'Documents used to confirm utility providers.',N'Check your lease and property manager instructions.');

INSERT INTO JL_STEP VALUES (7,3,1,N'加入条件を確認',N'勤務先の健康保険に入っていないか確認します。');
INSERT INTO JL_STEP VALUES (8,3,2,N'必要書類を準備',N'在留カード、パスポート、マイナンバー等を確認します。');
INSERT INTO JL_STEP VALUES (9,3,3,N'窓口で申請',N'14日以内に窓口へ届け出ます。');
INSERT INTO JL_STEP VALUES (10,4,1,N'年金区分を確認',N'第1号、第2号、第3号のどれに該当するか確認します。');
INSERT INTO JL_STEP VALUES (11,4,2,N'年金番号資料を準備',N'年金手帳または基礎年金番号通知書を確認します。');
INSERT INTO JL_STEP VALUES (12,4,3,N'加入手続き',N'住所地の区役所または年金事務所で手続きします。');
INSERT INTO JL_STEP VALUES (13,5,1,N'課税条件を確認',N'1月1日の住所と前年所得を確認します。');
INSERT INTO JL_STEP VALUES (14,5,2,N'通知を確認',N'港区または勤務先からの通知を確認します。');
INSERT INTO JL_STEP VALUES (15,6,1,N'入学条件を確認',N'住所地の学区と入学時期を確認します。');
INSERT INTO JL_STEP VALUES (16,6,2,N'学務課に申請',N'必要な資料を持って学務課に申請します。');
INSERT INTO JL_STEP VALUES (17,7,1,N'登録条件を確認',N'15歳以上で住民登録があるか確認します。');
INSERT INTO JL_STEP VALUES (18,7,2,N'印鑑を持って申請',N'登録する印鑑と在留カードを窓口に持参します。');
INSERT INTO JL_STEP VALUES (19,8,1,N'契約先を確認',N'賃貸契約書や管理会社の案内を確認します。');
INSERT INTO JL_STEP VALUES (20,8,2,N'使用開始を申請',N'電気、ガス、水道の各事業者へ連絡します。');

INSERT INTO JL_STEP_I18N VALUES (7,'ko',N'가입 조건 확인',N'회사 건강보험 가입 여부를 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (7,'en',N'Check eligibility',N'Confirm whether you have employer health insurance.');
INSERT INTO JL_STEP_I18N VALUES (8,'ko',N'필요 서류 준비',N'재류카드·여권·마이넘버 등을 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (8,'en',N'Prepare documents',N'Check your residence card, passport, and My Number information.');
INSERT INTO JL_STEP_I18N VALUES (9,'ko',N'창구에서 신청',N'14일 이내에 창구에 신고합니다.');
INSERT INTO JL_STEP_I18N VALUES (9,'en',N'File at the counter',N'File the notification within 14 days.');
INSERT INTO JL_STEP_I18N VALUES (10,'ko',N'연금 구분 확인',N'제1호·제2호·제3호 중 해당 구분을 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (10,'en',N'Check pension category',N'Confirm whether you are Category I, II, or III.');
INSERT INTO JL_STEP_I18N VALUES (11,'ko',N'연금번호 자료 준비',N'연금수첩 또는 기초연금번호 통지서를 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (11,'en',N'Prepare pension number proof',N'Check your pension book or Basic Pension Number Notice.');
INSERT INTO JL_STEP_I18N VALUES (12,'ko',N'가입 신청',N'주소지 구청 또는 연금사무소에서 신청합니다.');
INSERT INTO JL_STEP_I18N VALUES (12,'en',N'Complete enrollment',N'Complete the procedure at the municipal or pension office.');
INSERT INTO JL_STEP_I18N VALUES (13,'ko',N'과세 조건 확인',N'1월 1일 주소와 전년도 소득을 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (13,'en',N'Check tax conditions',N'Confirm your January 1 address and prior-year income.');
INSERT INTO JL_STEP_I18N VALUES (14,'ko',N'통지 확인',N'미나토구 또는 근무처의 통지를 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (14,'en',N'Check notices',N'Check notices from Minato City or your employer.');
INSERT INTO JL_STEP_I18N VALUES (15,'ko',N'입학 조건 확인',N'주소지 학구와 입학 시기를 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (15,'en',N'Check enrollment conditions',N'Confirm your school district and enrollment period.');
INSERT INTO JL_STEP_I18N VALUES (16,'ko',N'학무과 신청',N'필요한 자료를 가지고 학무과에 신청합니다.');
INSERT INTO JL_STEP_I18N VALUES (16,'en',N'Apply at School Affairs Section',N'Apply with the required documents.');
INSERT INTO JL_STEP_I18N VALUES (17,'ko',N'등록 조건 확인',N'15세 이상이고 주민등록이 있는지 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (17,'en',N'Check registration conditions',N'Confirm that you are at least 15 and registered as a resident.');
INSERT INTO JL_STEP_I18N VALUES (18,'ko',N'인감 지참 후 신청',N'등록할 인감과 재류카드를 창구에 지참합니다.');
INSERT INTO JL_STEP_I18N VALUES (18,'en',N'Apply with the seal',N'Bring the seal and residence card to the counter.');
INSERT INTO JL_STEP_I18N VALUES (19,'ko',N'계약처 확인',N'임대차계약서와 관리회사 안내를 확인합니다.');
INSERT INTO JL_STEP_I18N VALUES (19,'en',N'Confirm providers',N'Check your lease and property manager instructions.');
INSERT INTO JL_STEP_I18N VALUES (20,'ko',N'사용 시작 신청',N'전기·가스·수도 사업자에게 연락합니다.');
INSERT INTO JL_STEP_I18N VALUES (20,'en',N'Apply to start service',N'Contact the electricity, gas, and water providers.');

INSERT INTO JL_SOURCE VALUES (5,3,N'港区：国民健康保険の加入',N'https://www.city.minato.tokyo.jp/shikaku/kuse/kocho/faq/hoken/055.html',DATE '2026-09-29',DATE '2026-05-20');
INSERT INTO JL_SOURCE VALUES (6,4,N'日本年金機構：国民年金の加入',N'https://www.nenkin.go.jp/international/english/purpose/enroll/index.html',DATE '2026-09-29',DATE '2026-09-28');
INSERT INTO JL_SOURCE VALUES (7,5,N'港区：住民税',N'https://www.city.minato.tokyo.jp/easyjp/moving/taxes/residenttax.html',DATE '2026-09-29',DATE '2024-03-28');
INSERT INTO JL_SOURCE VALUES (8,6,N'港区：外国籍の子どもの区立学校への入学',N'https://www.city.minato.tokyo.jp/gakuji/faq/gaikokuseki.html',DATE '2026-09-29',DATE '2026-04-01');
INSERT INTO JL_SOURCE VALUES (9,7,N'港区：外国人の印鑑登録',N'https://www.city.minato.tokyo.jp/shibagaitou/kuse/kocho/faq/todokede/054.html',DATE '2026-09-29',DATE '2026-05-20');
INSERT INTO JL_SOURCE VALUES (10,8,N'港区：電気・ガス・水道などの手続き',N'https://www.city.minato.tokyo.jp/easyjp/moving/electrisitygaswater.html',DATE '2026-09-29',DATE '2024-03-28');
INSERT INTO JL_SOURCE_I18N VALUES (5,'ko',N'미나토구: 국민건강보험 가입');
INSERT INTO JL_SOURCE_I18N VALUES (5,'en',N'Minato City: National Health Insurance enrollment');
INSERT INTO JL_SOURCE_I18N VALUES (6,'ko',N'일본연금기구: 국민연금 가입');
INSERT INTO JL_SOURCE_I18N VALUES (6,'en',N'Japan Pension Service: National Pension enrollment');
INSERT INTO JL_SOURCE_I18N VALUES (7,'ko',N'미나토구: 주민세');
INSERT INTO JL_SOURCE_I18N VALUES (7,'en',N'Minato City: Resident tax');
INSERT INTO JL_SOURCE_I18N VALUES (8,'ko',N'미나토구: 외국 국적 자녀의 구립학교 입학');
INSERT INTO JL_SOURCE_I18N VALUES (8,'en',N'Minato City: Municipal school enrollment for foreign children');
INSERT INTO JL_SOURCE_I18N VALUES (9,'ko',N'미나토구: 외국인의 인감등록');
INSERT INTO JL_SOURCE_I18N VALUES (9,'en',N'Minato City: Personal seal registration for foreign residents');
INSERT INTO JL_SOURCE_I18N VALUES (10,'ko',N'미나토구: 전기·가스·수도 절차');
INSERT INTO JL_SOURCE_I18N VALUES (10,'en',N'Minato City: Electricity, gas, and water procedures');
COMMIT;
