-- 09: 신규 6개 절차의 서류 번역 및 추가 서류 보완
-- SOLO 계정에서 실행하세요. 이미 존재하는 행은 건너뛰므로 재실행할 수 있습니다.

INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 11,'ko',N'재류카드·여권',N'해외에서 전입하는 외국인 주민의 본인 확인에 필요합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=11 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 11,'en',N'Residence card and passport',N'Required to confirm the identity of a foreign resident moving in from abroad.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=11 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 12,'ko',N'기초연금번호를 확인할 수 있는 서류',N'국민연금 제1호 피보험자 절차에 해당하는 경우 확인합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=12 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 12,'en',N'Document showing your Basic Pension Number',N'Check this if you are subject to Category I National Pension enrollment.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=12 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 13,'ko',N'전년도 소득을 확인할 수 있는 자료',N'소득 신고 또는 주민세 확인이 필요한 경우 준비합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=13 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 13,'en',N'Proof of prior-year income',N'Prepare this when income reporting or resident-tax confirmation is required.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=13 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 14,'ko',N'자녀·보호자의 재류카드·여권',N'자녀와 보호자의 이름·주소 등을 확인할 때 사용합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=14 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 14,'en',N'Child and guardian residence cards or passports',N'Used to confirm the child and guardian names and addresses.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=14 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 15,'ko',N'등록할 인감과 재류카드',N'본인이 인감등록을 신청하는 경우 필요합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=15 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 15,'en',N'Seal to register and residence card',N'Required when you apply for seal registration in person.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=15 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 16,'ko',N'임대차계약서·관리회사 안내',N'전기·가스·수도의 계약처와 사용 시작 방법을 확인할 때 참고합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=16 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 16,'en',N'Lease and property manager instructions',N'Use these to identify utility providers and how to start service.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=16 AND language_code='en');

INSERT INTO JL_DOCUMENT (id,procedure_id,name,requirement,condition_text,display_order) SELECT 17,3,N'健康保険資格喪失証明書','CONDITIONAL',N'勤務先の健康保険をやめて国民健康保険に加入する場合。',2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT WHERE id=17);
INSERT INTO JL_DOCUMENT (id,procedure_id,name,requirement,condition_text,display_order) SELECT 18,4,N'マイナンバー確認書類と本人確認書類','CONDITIONAL',N'個人番号で届出する場合。基礎年金番号で届出する場合は不要なことがあります。',2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT WHERE id=18);
INSERT INTO JL_DOCUMENT (id,procedure_id,name,requirement,condition_text,display_order) SELECT 19,5,N'住民税の通知書・課税資料','CONDITIONAL',N'課税内容や申告状況を確認する場合。',2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT WHERE id=19);
INSERT INTO JL_DOCUMENT (id,procedure_id,name,requirement,condition_text,display_order) SELECT 20,6,N'就学申請・学校選択に関する通知','CONDITIONAL',N'学務課から案内を受けている場合。',2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT WHERE id=20);
INSERT INTO JL_DOCUMENT (id,procedure_id,name,requirement,condition_text,display_order) SELECT 21,7,N'委任状と代理人の本人確認書類','CONDITIONAL',N'代理人が申請または受領する場合。',2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT WHERE id=21);

INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 17,'ko',N'건강보험 자격상실증명서',N'직장 건강보험을 그만두고 국민건강보험에 가입하는 경우 준비합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=17 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 17,'en',N'Certificate of loss of employee health-insurance coverage',N'Prepare this when switching from employer insurance to National Health Insurance.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=17 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 18,'ko',N'마이넘버 확인서류와 본인확인서류',N'개인번호로 신고하는 경우 필요하며, 기초연금번호로 신고하면 필요하지 않을 수 있습니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=18 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 18,'en',N'My Number and identity documents',N'Required when filing with your Individual Number; it may not be needed when filing with your Basic Pension Number.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=18 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 19,'ko',N'주민세 통지서·과세 자료',N'과세 내용이나 신고 상태를 확인하는 경우 준비합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=19 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 19,'en',N'Resident-tax notice or tax documents',N'Prepare these when checking your tax assessment or filing status.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=19 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 20,'ko',N'취학 신청·학교 선택 관련 안내',N'학무과에서 안내를 받은 경우 함께 준비합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=20 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 20,'en',N'School-enrollment or school-choice notice',N'Bring this if it was issued by the School Affairs Section.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=20 AND language_code='en');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 21,'ko',N'위임장과 대리인 본인확인서류',N'대리인이 신청하거나 등록증을 받을 때 필요합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=21 AND language_code='ko');
INSERT INTO JL_DOCUMENT_I18N (document_id,language_code,name,condition_text) SELECT 21,'en',N'Power of attorney and proxy identity document',N'Required when a proxy applies or receives the registration certificate.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_I18N WHERE document_id=21 AND language_code='en');

INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 17,'ja',N'勤務先の健康保険をやめたことを確認する書類です。',N'勤務先または健康保険組合から交付された証明書を用意します。' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=17 AND language_code='ja');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 17,'ko',N'직장 건강보험 자격이 끝났음을 확인하는 서류입니다.',N'직장이나 건강보험조합에서 발급받은 증명서를 준비합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=17 AND language_code='ko');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 17,'en',N'Document confirming that employer health-insurance coverage ended.',N'Obtain the certificate from your employer or health-insurance society.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=17 AND language_code='en');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 18,'ja',N'個人番号または本人を確認するための書類です。',N'マイナンバーカード、通知カードまたは番号記載住民票と本人確認書類を確認します。' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=18 AND language_code='ja');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 18,'ko',N'개인번호와 본인을 확인하기 위한 서류입니다.',N'마이넘버카드·통지카드·번호가 적힌 주민표와 본인확인서류를 확인합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=18 AND language_code='ko');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 18,'en',N'Documents used to confirm your Individual Number and identity.',N'Check your My Number Card, Notice Card or My Number resident record, plus identity documents.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=18 AND language_code='en');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 19,'ja',N'住民税の課税内容や申告状況を確認する資料です。',N'区からの通知や所得資料など、手元にあるものを確認します。' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=19 AND language_code='ja');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 19,'ko',N'주민세 과세 내용과 신고 상태를 확인하는 자료입니다.',N'구청 통지서와 소득 자료 등 가지고 있는 자료를 확인합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=19 AND language_code='ko');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 19,'en',N'Materials used to check resident-tax assessment and filing status.',N'Check notices from the city and any income documents you have.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=19 AND language_code='en');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 20,'ja',N'学校への就学手続きに関する案内です。',N'学務課から届いた申請書や通知を確認します。' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=20 AND language_code='ja');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 20,'ko',N'학교 취학 절차와 관련된 안내입니다.',N'학무과에서 받은 신청서나 안내문을 확인합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=20 AND language_code='ko');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 20,'en',N'Guidance for the school-enrollment procedure.',N'Check application forms or notices received from the School Affairs Section.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=20 AND language_code='en');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 21,'ja',N'代理人が手続きする場合の委任と本人確認に使う書類です。',N'本人が自署押印した委任状と代理人の本人確認書類を用意します。' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=21 AND language_code='ja');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 21,'ko',N'대리인이 절차를 진행할 때 필요한 위임·본인확인 서류입니다.',N'본인이 자필 서명·날인한 위임장과 대리인의 본인확인서류를 준비합니다.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=21 AND language_code='ko');
INSERT INTO JL_DOCUMENT_GUIDE (document_id,language_code,description,preparation_note) SELECT 21,'en',N'Documents for authorization and identity checks when using a proxy.',N'Prepare a signed and sealed power of attorney and the proxy identity document.' FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM JL_DOCUMENT_GUIDE WHERE document_id=21 AND language_code='en');

COMMIT;
