-- 13: JAPAN LIFE GUIDE 커뮤니티 기능용 테이블
-- 기존 테이블·데이터를 삭제하지 않습니다. Oracle SQL Developer에서 한 번 실행합니다.
-- 재실행 시 이미 존재하는 테이블·시퀀스는 건너뜁니다.
DECLARE
  PROCEDURE create_if_missing(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = UPPER(p_name);
    IF v_count = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
  PROCEDURE sequence_if_missing(p_name VARCHAR2, p_sql VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = UPPER(p_name);
    IF v_count = 0 THEN EXECUTE IMMEDIATE p_sql; END IF;
  END;
BEGIN
  create_if_missing('JL_COMMUNITY_POST', 'CREATE TABLE JL_COMMUNITY_POST (id NUMBER(19) PRIMARY KEY, member_id NUMBER(19) NOT NULL REFERENCES JL_MEMBER(id), category VARCHAR2(30) NOT NULL, title NVARCHAR2(200) NOT NULL, body NCLOB NOT NULL, status VARCHAR2(20) DEFAULT ''ACTIVE'' NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jl_community_post_category_ck CHECK (category IN (''ADMIN'', ''HOME'', ''STUDENT'', ''WORK'', ''MEETUP'', ''GENERAL'')), CONSTRAINT jl_community_post_status_ck CHECK (status IN (''ACTIVE'', ''HIDDEN'', ''DELETED'')))');
  create_if_missing('JL_COMMUNITY_COMMENT', 'CREATE TABLE JL_COMMUNITY_COMMENT (id NUMBER(19) PRIMARY KEY, post_id NUMBER(19) NOT NULL REFERENCES JL_COMMUNITY_POST(id), member_id NUMBER(19) NOT NULL REFERENCES JL_MEMBER(id), body NCLOB NOT NULL, status VARCHAR2(20) DEFAULT ''ACTIVE'' NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jl_community_comment_status_ck CHECK (status IN (''ACTIVE'', ''HIDDEN'', ''DELETED'')))');
  create_if_missing('JL_COMMUNITY_LIKE', 'CREATE TABLE JL_COMMUNITY_LIKE (post_id NUMBER(19) NOT NULL REFERENCES JL_COMMUNITY_POST(id), member_id NUMBER(19) NOT NULL REFERENCES JL_MEMBER(id), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jl_community_like_pk PRIMARY KEY (post_id, member_id))');
  create_if_missing('JL_COMMUNITY_REPORT', 'CREATE TABLE JL_COMMUNITY_REPORT (id NUMBER(19) PRIMARY KEY, post_id NUMBER(19) REFERENCES JL_COMMUNITY_POST(id), comment_id NUMBER(19) REFERENCES JL_COMMUNITY_COMMENT(id), member_id NUMBER(19) NOT NULL REFERENCES JL_MEMBER(id), reason NVARCHAR2(500) NOT NULL, status VARCHAR2(20) DEFAULT ''OPEN'' NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jl_community_report_target_ck CHECK ((post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)), CONSTRAINT jl_community_report_status_ck CHECK (status IN (''OPEN'', ''RESOLVED'', ''REJECTED'')))');
  create_if_missing('JL_COMMUNITY_REPORT_AUDIT', 'CREATE TABLE JL_COMMUNITY_REPORT_AUDIT (id NUMBER(19) PRIMARY KEY, report_id NUMBER(19) NOT NULL REFERENCES JL_COMMUNITY_REPORT(id), admin_member_id NUMBER(19) NOT NULL REFERENCES JL_MEMBER(id), action_type VARCHAR2(20) NOT NULL, previous_report_status VARCHAR2(20) NOT NULL, new_report_status VARCHAR2(20) NOT NULL, target_type VARCHAR2(20) NOT NULL, previous_content_status VARCHAR2(20), new_content_status VARCHAR2(20), reason NVARCHAR2(1000), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jcr_audit_action_ck CHECK (action_type IN (''REJECT'',''HIDE'',''DELETE'')), CONSTRAINT jcr_audit_target_ck CHECK (target_type IN (''POST'',''COMMENT'')), CONSTRAINT jcr_audit_status_ck CHECK (previous_report_status IN (''OPEN'',''RESOLVED'',''REJECTED'') AND new_report_status IN (''OPEN'',''RESOLVED'',''REJECTED'')))');
  create_if_missing('JL_COMMUNITY_IMAGE', 'CREATE TABLE JL_COMMUNITY_IMAGE (id NUMBER(19) PRIMARY KEY, post_id NUMBER(19) NOT NULL REFERENCES JL_COMMUNITY_POST(id), original_name NVARCHAR2(255) NOT NULL, stored_name VARCHAR2(255) NOT NULL, content_type VARCHAR2(100) NOT NULL, file_size NUMBER(19) NOT NULL, display_order NUMBER(5) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jl_community_image_size_ck CHECK (file_size > 0))');
  sequence_if_missing('JL_COMMUNITY_POST_SEQ', 'CREATE SEQUENCE JL_COMMUNITY_POST_SEQ START WITH 1000 INCREMENT BY 1');
  sequence_if_missing('JL_COMMUNITY_COMMENT_SEQ', 'CREATE SEQUENCE JL_COMMUNITY_COMMENT_SEQ START WITH 1000 INCREMENT BY 1');
  sequence_if_missing('JL_COMMUNITY_REPORT_SEQ', 'CREATE SEQUENCE JL_COMMUNITY_REPORT_SEQ START WITH 1000 INCREMENT BY 1');
  sequence_if_missing('JL_COMMUNITY_REPORT_AUDIT_SEQ', 'CREATE SEQUENCE JL_COMMUNITY_REPORT_AUDIT_SEQ START WITH 1000 INCREMENT BY 1');
  sequence_if_missing('JL_COMMUNITY_IMAGE_SEQ', 'CREATE SEQUENCE JL_COMMUNITY_IMAGE_SEQ START WITH 1000 INCREMENT BY 1');
END;
/
COMMIT;

SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME LIKE 'JL_COMMUNITY%';
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE 'JL_COMMUNITY%';
