-- 14: 커뮤니티 이미지 저장 구조 추가
-- 기존 테이블과 데이터는 삭제하지 않습니다. 재실행 가능합니다.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'JL_COMMUNITY_IMAGE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE JL_COMMUNITY_IMAGE (id NUMBER(19) PRIMARY KEY, post_id NUMBER(19) NOT NULL REFERENCES JL_COMMUNITY_POST(id), original_name NVARCHAR2(255) NOT NULL, stored_name VARCHAR2(255) NOT NULL, content_type VARCHAR2(100) NOT NULL, file_size NUMBER(19) NOT NULL, display_order NUMBER(5) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT jl_community_image_size_ck CHECK (file_size > 0))';
  END IF;
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'JL_COMMUNITY_IMAGE_SEQ';
  IF v_count = 0 THEN EXECUTE IMMEDIATE 'CREATE SEQUENCE JL_COMMUNITY_IMAGE_SEQ START WITH 1000 INCREMENT BY 1'; END IF;
END;
/
COMMIT;
SELECT TABLE_NAME FROM USER_TABLES WHERE TABLE_NAME = 'JL_COMMUNITY_IMAGE';
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'JL_COMMUNITY_IMAGE_SEQ';
