-- 16: 커뮤니티 게시글 조회수 추가
-- 기존 테이블과 데이터는 삭제하지 않습니다.
-- 재실행해도 이미 컬럼이 있으면 건너뜁니다.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'JL_COMMUNITY_POST'
     AND COLUMN_NAME = 'VIEW_COUNT';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE
      'ALTER TABLE JL_COMMUNITY_POST ADD (VIEW_COUNT NUMBER(19) DEFAULT 0 NOT NULL)';
  END IF;
END;
/
COMMIT;

SELECT COLUMN_NAME, DATA_TYPE, DATA_DEFAULT, NULLABLE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'JL_COMMUNITY_POST'
   AND COLUMN_NAME = 'VIEW_COUNT';
